# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Submission.destroy_all
Transition.destroy_all
Position.destroy_all

# create all positions
@open_guard = Position.create!(name: "Open Guard", description: "The open guard is a highly variable position where the attacker is on thier feet or knees, and the defender is sitting or lying on thier back. The defender will typically try to control the attacker's wrists with grips, while pressuring them with thier feet, aiming to sweep. The attacker will typically try to get past the defender's legs by staying mobile and controlling thier feet with grips.", img_url: "https://www.jiujitsutimes.com/wp-content/uploads/Bernardo-Faria-BJJ-3.png")
@half_guard = Position.create!(name: "Half Guard", description: "This is a versatile position in which the person on bottom is using both legs to  control a single leg of the opponent. While Half Guard does not offer as much safety as Full Guard, it does offer a greater amount of mobility. This position is difficult to master, but those that do master it tend to be the most difficult opponents to roll with.", img_url: "https://i.ytimg.com/vi/tioQH8Fwg30/maxresdefault.jpg")
@closed_guard = Position.create!(name: "Closed Guard", description: "This position is often the first position learned in Brazilian Jiu-Jitsu, yet is one of the last to truly be mastered. It is widely considered to be a safe position for the person on the bottom since it limits the movement of the opponent, as well as greatly reduces any strength advantage that the opponent might have. From this position, the person on bottom has access to a variety of sweeps and submissions, and they are relatively safe from being submitted in this position.", img_url: "https://www.attacktheback.com/wp-content/uploads/2014/12/closed-guard1.jpg")
@butterfly_guard = Position.create!(name: "Butterfly Guard", description: "This position is so named because the legs of the person on bottom are open and active, like the wings of a butterfly, with the tops of the defender's feet typically fixed to the insides of the attacker's thighs. This position is similar to Full Guard in that the legs are used to monitor and affect the distance/position of the opponent, but Butterfly Guard tends to be a more active position since the person on top is not being squeezed and held in place.", img_url: "http://www.grapplearts.com/wp-content/uploads/2013/03/What-is-the-Butterfly-Guard.png")
@side_control = Position.create!(name: "Side Control", description: "This is a very strong control position for the person on top and one of the most difficult positions to escape from when on bottom since the person on top is controlling both arms of their opponent, as well as isolating their hips and legs. The top position has a few variations that are used based on the escapes being attempted by the defender.", img_url: "https://www.attacktheback.com/wp-content/uploads/2016/09/Opener3.jpg")
@turtle = Position.create!(name: "Turtle", description: "This position is a purely defensive position, and is usually achieved when the person on bottom istrying to recover from a worse position. Players typically don’t want to be in this position for long, as it does not have very many options for sweeps or submissions. Occasionally a high-ranking or larger opponent will “Turtle up” against a lower-ranking or smaller opponent as a way to 1) frustrate them or 2) give them an opportunity to work from the top without sacrificing much in their position.", img_url: "https://supersoldierproject.com/wp-content/uploads/2021/07/BJJ-Turtle.jpeg")
@mount = Position.create!(name: "Mount", description: "For the person on the bottom, this is position is the opposite of being in Full Guard.  The top person has a huge advantage in this position because they are able to avoid the protection normally offered by their opponent's legs. There are a wide variety of transitions and submissions from this position. It is very difficult for the bottom person to transition into a better position.", img_url: "https://cdn.shopify.com/s/files/1/0363/5125/articles/Keys_to_Mount.png?v=1579429130")
@knee_on_belly = Position.create!(name: "Knee on Belly", description: "This is a favored position for the active roller, though they tend to not stay here for long. This position is usually achieved when the attacker is able to pass the defender's open Guard or as a transition from Side Control to another dominant position. From this position, the person on top can monitor the movement of their opponent and quickly react. Given enough time, the person on bottom will escape this position, so this position is often used as a stepping stone to a stronger position or to a sneaky submission. You'll see a large number of Lapel Chokes and Armbars come from this position, as well as transitions to Side Control or Mount.", img_url: "https://i0.wp.com/thatgirlisfunny2.com/wp-content/uploads/2018/10/bjj-knee-on-belly.jpg?ssl=1")
@back_control = Position.create!(name: "Back Control", description: "This position is sometimes referred to as “taking the back”.  The biggest benefit of this position is that it effectively neutralizes any size or strength advantage the opponent once had. When a smaller person is rolling against a bigger opponent, this position becomes the Holy Grail. From Back Mount, you can easily transition to a large number of submissions including chokes and armbars.", img_url: "https://bjjsouthside.com/wp-content/uploads/2017/05/uflacker-back.jpg")

puts "#{Position.count} positions created!"

# create some submissions
Submission.create!(name: "Triangle Choke From Spider Guard", description: "", img_url: "", position: @open_guard)
Submission.create!(name: "Kimura From Half Guard (Top)", description: "The kimura can be applied from the top position of half guard", img_url: "https://www.jiujitsutimes.com/wp-content/uploads/Georges-St-Pierre-2.png", position: @half_guard)
Submission.create!(name: "Triangle Choke From Closed Guard", description: "The triangle involves having your opponent's neck and arm in between your legs in a triangle shape and it ends by flexing your quads and hamstrings in a certain way that chokes your opponent.", img_url: "https://www.bjjsuccess.com/wp-content/uploads/2020/04/Triangle.jpg", position: @closed_guard)
Submission.create!(name: "Reverse Armbar From Butterfly Guard", description: "The reverse armbar from butterfly guard is best done when your opponent is reaching for your head. Grip their elbow, and pin their wrist with your shoulder and head. Stretch your opponent's arm out by pushing off them to the side, and make sure thier elbow is pointed upward. This submission comes on quickly, so take care to not injure your opponent.", img_url: "", position: @butterfly_guard)
Submission.create!(name: "Guillotine From Side Control", description: "The guillotine involves wrapping your arm over the back of your opponent's neck, trapping it to your side, then squeezing and adjusting angle until your opponent is choked.", img_url: "https://i.pinimg.com/originals/cd/e2/92/cde2927f216bc3b9d1da51c6179dc350.jpg", position: @side_control)
Submission.create!(name: "Americana From Mount", description: "The aim of the americana is to isolate your opponent's shoulder joint. Thier wrist is pinned to the mat, while thier elbow is forced up.", img_url: "https://i.ytimg.com/vi/EZwWF4gjKKE/maxresdefault.jpg", position: @mount)
Submission.create!(name: "Armbar From Knee On Belly", description: "The armbar from knee on belly requires you to isolate your opponent's arm, pinning it to your chest, then throw your trailing leg over thier face or neck. Because you have to fall to your back, this can be a risky submission, since your opponent can gain position if the submission fails.", img_url: "https://i.ytimg.com/vi/XQ71letzL7w/maxresdefault.jpg", position: @knee_on_belly)
Submission.create!(name: "Rear Naked Choke", description: "The rear naked choke is applied by squeezing your opponent's neck with your bicep and forearm. Often added pressure is applied by pushing the back of your opponent's head forward into the choking arm.", img_url: "http://flo-static-assets.s3.amazonaws.com/uploads/api/55e9aae7875af.jpeg", position: @back_control)

puts "#{Submission.count} submissions created!"

# create some transitions
Transition.create!(name: "Butterfly Sweep From Butterfly Guard", description: "The butterfly sweep is one of the most simple and effective sweeps in Brazilian jiu-jitsu. The goal is to elevate your opponent by thier legs with your feet, and roll them over to one side. As you roll, come up to mount, securing the sweep.", img_url: "https://cdn.shopify.com/s/files/1/1800/2299/articles/nino-butterfly-sweep-david_1024x1024.jpg?v=1501474878", start_id: @butterfly_guard.id, finish_id: @mount.id)
Transition.create!(name: "Coyote Sweep", description: "The coyote sweep was developed by Lucas Leite to bring you from half guard bottom to mount. To begin, you must 1) have your top knee framed against your opponent's chest or hips, and 2) underhook your top arm, grabbing thier waist or side. Then transition to your knees, trapping your opponent's leg with the previously framing leg. From here, your opponent will likely wizzer your underhook, stopping you from taking their back, so typically you would reach for thier knee for a double-leg takedown. At that point, you can secure mount and the sweep.", img_url: "https://www.sampabjj.com/wp-content/uploads/2017/10/Screen-Shot-2017-11-12-at-05.51.44-1024x610.png", start_id: @half_guard.id, finish_id: @mount.id)
Transition.create!(name: "Shrimp Escape From Side Control", description: "The shrimp escape or hip escape is fundamental to Brazilian jiu-jitsu. When performing this escape, the goal is to bridge which lifts your opponet, then shrimp your hips as far back as you can, creating space. Capture that space by framing your arms and shooting your knee up, where you are effectively in open guard.", img_url: "https://www.jiujitsutimes.com/wp-content/uploads/lachlan-giles-4.png", start_id: @side_control.id, finish_id: @closed_guard.id)
Transition.create!(name: "UPA Escape From Mount", description: "Probably the most popular mount escape, you begin the UPA escape by bridging into your opponent's hips, breaking their posture, capturing an arm with a 2 on 1 grip, capturing their foot on the same side, and with a powerful bridge roll your opponent over to gain the top position.", img_url: "https://bjjmoves.com/wp-content/uploads/2016/03/Upa-Bridge-jiu-jitsu-escape-move-2.jpg", start_id: @mount.id, finish_id: @closed_guard.id)
Transition.create!(name: "Shrimp Escape From Back Control", description: "Shrimping is fundamental to Brazilian jiu-jitsu. When performing this escape it is important to protect your neck by keeping your chin tucked and defending against chokes with your hands. Meanwhile work your shoulders off your opponent's chest and get them on the mat. From here your opponent has a good opportuntiy to mount, since you are on your back, so shrimp your hips back as you push off, framing with your arms. Then you can capture the space by framing your legs between you and your opponent, getting to open guard.", img_url: "https://cdn.evolve-mma.com/wp-content/uploads/2018/11/BJJ-Back-Mount.jpg", start_id: @back_control.id, finish_id: @open_guard.id)
Transition.create!(name: "Turtle Escape To Closed Guard", description: "When defending in turtle, and your opponent is moving from pressuring on the hips to pressuring on the upper back, roll onto your shoulder. With wide legs, roll into your opponent and wrap up into closed guard.", img_url: "https://i.imgur.com/u0wYZMQ.png", start_id: @turtle.id, finish_id: @closed_guard.id)
Transition.create!(name: "Toreando Pass", description: "The Toreando pass is done by pinning and moving your opponents legs out of the way of your own. This will expose your opponent's side allowing you to gain knee on belly. Grips are essential to this pass, and a variety of grips can be used, but the aim is to maintain control over your opponent's legs.", img_url: "https://i1.wp.com/bjjtribes.com/wp-content/uploads/2020/08/lo.jpg?fit=800%2C534&ssl=1", start_id: @open_guard.id, finish_id: @knee_on_belly.id)
Transition.create!(name: "Sitting Closed Guard Pass", description: "It is vital to maintain posture while executing this pass. Move a hand to your opponent's hip and apply pressure on the inside of their thigh with your elbow. On that same side, pressure your knee into their hip on the under-side. Then step your other foot out, and turn your hips and chest out away from the pressuring elbow, lenghthening your opponent's leg. Then pressure your opponent's knee in front of you with your free hand, and open the guard by pushing backward with your hips and framing against the knee.", img_url: "", start_id: @closed_guard.id, finish_id: @open_guard.id)
Transition.create!(name: "Knee On Belly To Mount", description: "Moving to mount from knee on belly is fairly simple, but there are a few things to keep in mind as to not lose control. First, maintain pressure of your whole shin as you slide your knee from your opponent's belly to the mat. Then windshield pivot your shin from the knee, being careful to not let your lower leg be caught by your opponent's legs.", img_url: "", start_id: @knee_on_belly.id, finish_id: @mount.id)

puts "#{Transition.count} transitions created!"
